PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12
  train_size: 0.6
  val_size: 0.2
  time_of_day: True
  day_of_week: True
  lr: 0.01
  epsilon: 0.001
  weight_decay: 0.01
  milestones: [30, 50, 70]
  lr_decay_ratio: 0.1
  batch_size: 32
  epochs: 100
  early_stop: 30
  use_cl: False
  cl_step_size: 2000
  max_grad_norm: 5.0
  lamb1: 0.1
  lamb2: 0.05
  seed: 101

  model_args:
    num_nodes: 170
    input_dim: 1
    output_dim: 1
    horizon: 12
    rnn_units: 64
    num_layers: 1
    cheb_k: 3
    ycov_dim: 2
    mem_num: 40
    mem_dim: 64
    time_dim: 20
    adp_dim: 20
    cl_decay_steps: 2000
    use_curriculum_learning: True

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.01
  epsilon: 0.001
  weight_decay: 0.01
  milestones: [50, 100, 110]
  lr_decay_ratio: 0.1
  batch_size: 64
  epochs: 120
  early_stop: 30
  use_cl: False
  cl_step_size: 2000
  lamb1: 0.05
  lamb2: 0.01
  max_grad_norm: 5.0
  seed: 72


  model_args:
    num_nodes: 883
    input_dim: 1
    output_dim: 1
    horizon: 12
    rnn_units: 80
    num_layers: 1
    cheb_k: 3
    ycov_dim: 2
    mem_num: 40
    mem_dim: 80
    time_dim: 20
    adp_dim: 20
    cl_decay_steps: 2000
    use_curriculum_learning: True

PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.01
  epsilon: 0.001
  weight_decay: 0.005
  milestones: [30, 50, 70]
  lr_decay_ratio: 0.1
  batch_size: 32
  epochs: 100
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  lamb1: 0.1
  lamb2: 0.1
  max_grad_norm: 5.0
  seed: 45


  model_args:
    num_nodes: 307
    input_dim: 1
    output_dim: 1
    horizon: 12
    rnn_units: 64
    num_layers: 1
    cheb_k: 3
    ycov_dim: 2
    mem_num: 40
    mem_dim: 64
    time_dim: 20
    adp_dim: 20
    cl_decay_steps: 2000
    use_curriculum_learning: True

PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.01
  epsilon: 0.001
  weight_decay: 0.001
  milestones: [30, 50, 70]
  lr_decay_ratio: 0.1
  batch_size: 32
  epochs: 100
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  lamb1: 0.1
  lamb2: 0.1
  max_grad_norm: 5.0
  seed: 30


  model_args:
    num_nodes: 358
    input_dim: 1
    output_dim: 1
    horizon: 12
    rnn_units: 52
    num_layers: 1
    cheb_k: 3
    ycov_dim: 2
    mem_num: 40
    mem_dim: 64
    time_dim: 20
    adp_dim: 20
    cl_decay_steps: 2000
    use_curriculum_learning: True

METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.01
  epsilon: 0.001
  weight_decay: 0.01
  milestones: [30, 50, 70]
  lr_decay_ratio: 0.1
  batch_size: 64
  epochs: 100
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  lamb1: 0.1
  lamb2: 0.05
  max_grad_norm: 5.0
  seed: 54


  model_args:
    num_nodes: 207
    input_dim: 1
    output_dim: 1
    horizon: 12
    rnn_units: 64
    num_layers: 1
    cheb_k: 3
    ycov_dim: 2
    mem_num: 40
    mem_dim: 64
    time_dim: 20
    adp_dim: 20
    cl_decay_steps: 2000
    use_curriculum_learning: True

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.01
  epsilon: 0.001
  weight_decay: 0.01
  milestones: [30, 50, 70]
  lr_decay_ratio: 0.1
  batch_size: 64
  epochs: 100
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  lamb1: 0.01
  lamb2: 0.01
  max_grad_norm: 5.0
  seed: 92


  model_args:
    num_nodes: 325
    input_dim: 1
    output_dim: 1
    horizon: 12
    rnn_units: 64
    num_layers: 1
    cheb_k: 3
    ycov_dim: 2
    mem_num: 40
    mem_dim: 64
    time_dim: 20
    adp_dim: 20
    cl_decay_steps: 2000
    use_curriculum_learning: True

